export const AUTH_ROUTE = '/auth';
export const HOME_ROUTE = '/';
export const STORY_ROUTE = '/scroll';
export const BOOK_ROUTE = "/book/:bookId";
export const READ_BOOK_ROUTE="/read/:bookId"
export const ALLBOOKS_ROUTE = "/books";
export const BOOKSBYNAME_ROUTE = "/booksByName";
export const BOOKSBYCATEGORY = "books-by-category";
export const HISTORY_ROUTE = "/history"